import './globals.css'
import { Be_Vietnam_Pro } from 'next/font/google'
import getCurrentUser from '../action/getCurrentUser'
import { Toaster } from 'react-hot-toast'
import Navbar from '@/components/navbar/Navbar'
import Provider from '@/components/provider/Provider'
const BVP = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getCurrentUser()
  return (
    <html lang="en">
      <body className={BVP.className}>
        <Provider>
          <Toaster/>
          <Navbar session={session} />
          <div className=" mt-[82px]">
            <div className="h-full   w-full">
              <div className="grid grid-cols-5  w-full h-full">
                <div className=' hidden lg:block lg:col-span-1 h-full'></div>
                <div
                  className="
                      col-span-5 
                      lg:col-span-3
                      
                      
                      ">
                  {children}
                </div>
                <div className=' hidden lg:block lg:col-span-1 h-full'></div>
              </div>
            
            </div>
          </div>
        </Provider>

      </body>
    </html>
  )
}
